### ISSUE TITLE
Files don't always update correctly: files can exist twice in a single framework

### ISSUE THREAD

**Issue by mauritslamers** [sproutcore/build-tools#33]
Using the BT I ran into an issue already reported earlier by Topher Fangio, which is that sometimes certain files don't seem to get updated when a file on disk changes.
Investigating this problem, I found out that it is possible somehow that a file gets created twice in the same framework.
The fsevents process (on Mac) will update a different file object than the server will return, resulting in the impression that a file doesn't get updated, where it effectively does, but the wrong file object is returned by the server. It is possible that this is triggered in a delete / create (rename) process where a new file is added to the system where an existing file already has that path, or the original file didn't get destroyed.

**Comment by nicolasbadia** [comment]
Isn't this issue fixed?

**Comment by mauritslamers** [comment]
I think so too. I haven't seen it since.
